# Generated by Django 3.0.2 on 2020-03-11 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiledata',
            name='Branch',
        ),
        migrations.RemoveField(
            model_name='profiledata',
            name='College',
        ),
        migrations.RemoveField(
            model_name='profiledata',
            name='Company',
        ),
        migrations.RemoveField(
            model_name='profiledata',
            name='Connection',
        ),
        migrations.RemoveField(
            model_name='profiledata',
            name='Degree',
        ),
        migrations.RemoveField(
            model_name='profiledata',
            name='Degree_Year',
        ),
        migrations.RemoveField(
            model_name='profiledata',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='profiledata',
            name='Joining',
        ),
        migrations.RemoveField(
            model_name='profiledata',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='profiledata',
            name='Stream',
        ),
        migrations.RemoveField(
            model_name='profiledata',
            name='Work_profile',
        ),
        migrations.RemoveField(
            model_name='profiledata',
            name='Year',
        ),
    ]
