# Generated by Django 3.0.2 on 2020-03-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0002_auto_20200311_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledata',
            name='Branch',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profiledata',
            name='College',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profiledata',
            name='Company',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profiledata',
            name='Connection',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profiledata',
            name='Degree',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profiledata',
            name='Degree_Year',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profiledata',
            name='Image',
            field=models.ImageField(default='AlumniTracker/images/profile.png', upload_to='AlumniTracker/images'),
        ),
        migrations.AddField(
            model_name='profiledata',
            name='Joining',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profiledata',
            name='Location',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profiledata',
            name='Stream',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profiledata',
            name='Work_profile',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profiledata',
            name='Year',
            field=models.IntegerField(null=True),
        ),
    ]
