# Generated by Django 3.0.2 on 2020-03-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0003_auto_20200311_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RollNo', models.CharField(max_length=20, null=True, unique=True)),
                ('Year', models.IntegerField(null=True)),
                ('Branch', models.CharField(max_length=20, null=True)),
                ('Image', models.ImageField(default='AlumniTracker/images/profile.png', upload_to='AlumniTracker/images')),
                ('Location', models.CharField(max_length=30, null=True)),
                ('Work_profile', models.CharField(max_length=30, null=True)),
                ('Connection', models.CharField(max_length=10, null=True)),
                ('Company', models.CharField(max_length=50, null=True)),
                ('Joining', models.CharField(max_length=20, null=True)),
                ('College', models.CharField(max_length=50, null=True)),
                ('Degree', models.CharField(max_length=20, null=True)),
                ('Stream', models.CharField(max_length=20, null=True)),
                ('Degree_Year', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ProfileData',
        ),
    ]
