# Generated by Django 3.0.2 on 2020-03-14 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0006_auto_20200314_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Degree_Year',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Stream',
        ),
    ]
