# Generated by Django 3.0.2 on 2020-03-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0007_auto_20200314_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Location',
        ),
        migrations.AddField(
            model_name='profile',
            name='Current_Location',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedIn_Link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Branch',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='College',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Degree',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Year',
            field=models.IntegerField(null=True),
        ),
    ]
