# Generated by Django 3.0.2 on 2020-04-01 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0010_auto_20200401_1344'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scrapper_Data',
        ),
    ]
