# Generated by Django 3.0.2 on 2020-04-01 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tracker', '0015_auto_20200401_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapper_data',
            name='profile',
        ),
        migrations.AddField(
            model_name='scrapper_data',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
