# Generated by Django 3.0.2 on 2020-04-01 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0016_auto_20200401_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapper_data',
            name='user',
        ),
        migrations.AddField(
            model_name='scrapper_data',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Tracker.Profile'),
            preserve_default=False,
        ),
    ]
