# Generated by Django 3.0.2 on 2020-04-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0018_remove_scrapper_data_degree_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapper_data',
            name='degree_year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
