# Generated by Django 3.0.2 on 2020-04-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0019_scrapper_data_degree_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('post_img', models.ImageField(default='AlumniTracker/images/bg.jpg', upload_to='AlumniTracker/images')),
            ],
        ),
    ]
