# Generated by Django 3.0.2 on 2020-04-08 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0020_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='College',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Company',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Connection',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Degree',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Joining',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Work_profile',
        ),
    ]
