# Generated by Django 3.0.2 on 2020-04-08 05:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0023_auto_20200408_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Up to 10 digits allowed.', regex='^[6789]\\d{10}$ ')]),
        ),
    ]
