# Generated by Django 3.0.2 on 2020-04-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0029_auto_20200408_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='linkedIn_Link',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
