# Generated by Django 3.0.2 on 2020-04-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0031_blog_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
