# Generated by Django 3.0.2 on 2020-04-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0032_profile_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestedBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(default='image/bg.jpg', upload_to='AlumniTracker/images')),
                ('created', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Requested'), (1, 'Publish')], default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='post_img',
            field=models.ImageField(default='image/bg.jpg', upload_to='AlumniTracker/images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Image',
            field=models.ImageField(default='image/profile.png', upload_to='AlumniTracker/images'),
        ),
    ]
