# Generated by Django 3.0.2 on 2020-04-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0033_auto_20200412_1748'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestedBlog',
        ),
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.IntegerField(choices=[(0, 'Requested'), (1, 'Publish')], default=0),
        ),
    ]
