# Generated by Django 3.0.2 on 2020-04-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0034_auto_20200412_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post_img',
            field=models.ImageField(default='static/images/bg.jpg', upload_to='AlumniTracker/images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Image',
            field=models.ImageField(default='static/images/profile.png', upload_to='AlumniTracker/images'),
        ),
    ]
