# Generated by Django 3.0.2 on 2020-04-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0036_auto_20200412_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.TextField(default='Admin', max_length=50),
        ),
    ]
