# Generated by Django 3.0.2 on 2020-06-01 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0038_auto_20200413_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapper_data',
            name='college_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
